# -*- coding: utf-8 -*-
"""[Data] line graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oA5VloPnxS3acBK8gDI1Zrjq0Eff16w4
"""

import pandas as pd
from matplotlib import pyplot as plt
from google.colab import drive

drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/Historical Data_3.csv",encoding='cp1252')
df['year_quarter'] = df['Year'].map(str) +" "+ df['quarter'].map(str) +"Q"

df_example = df[(df['city1']=='Albany, NY') & (df['city2']=='Washington, DC (Metropolitan Area)')]

df_example[['Year','quarter','city1','city2','fare','fare_lg','fare_low', 'year_quarter']]

df_sorted = df_example.sort_values(['year_quarter'])

plt.plot(df_sorted['year_quarter'], df_sorted['fare'], label="Fare_average", color='black',linewidth = 2)

plt.xlabel('Year Quarter')
plt.ylabel('Fare')
plt.xticks(rotation=45)
plt.legend()
plt.show()

